"""empty message

Revision ID: 81f15e66a1dd
Revises: 
Create Date: 2025-04-12 19:28:29.682928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f15e66a1dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_countries', sa.Column('hh', sa.Float(), nullable=False))
    op.alter_column('point_countries', 'buy',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point_countries', 'buy',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('point_countries', 'hh')
    # ### end Alembic commands ###
