"""Initial migration

Revision ID: a5762c5ddb26
Revises: 81f15e66a1dd
Create Date: 2025-04-15 22:39:01.218823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5762c5ddb26'
down_revision: Union[str, None] = '81f15e66a1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates_cards', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('exchange_rates_internet_bank', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('exchange_rates_mobile_app', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('exchange_rates_office_cash', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('exchange_rates_office_cashless', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates_office_cashless', 'quantity')
    op.drop_column('exchange_rates_office_cash', 'quantity')
    op.drop_column('exchange_rates_mobile_app', 'quantity')
    op.drop_column('exchange_rates_internet_bank', 'quantity')
    op.drop_column('exchange_rates_cards', 'quantity')
    # ### end Alembic commands ###
