"""добавил столбец для фитбека

Revision ID: 138bf2ac12e2
Revises: 2deea52a1436
Create Date: 2025-04-27 00:07:24.480509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138bf2ac12e2'
down_revision: Union[str, None] = '2deea52a1436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servis_fitbacks', sa.Column('comments', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servis_fitbacks', 'comments')
    # ### end Alembic commands ###
