"""cоздал таблицу с servis_fitbacks 

Revision ID: 22ae72215c8b
Revises: d6ad83fffa43
Create Date: 2025-04-19 20:58:55.662759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ae72215c8b'
down_revision: Union[str, None] = 'd6ad83fffa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servis_fitbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer'),
    sa.UniqueConstraint('question')
    )
    op.create_index(op.f('ix_servis_fitbacks_category'), 'servis_fitbacks', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servis_fitbacks_category'), table_name='servis_fitbacks')
    op.drop_table('servis_fitbacks')
    # ### end Alembic commands ###
