"""начал делать банковские таблицы

Revision ID: 2d988d3a3121
Revises: 625160481821
Create Date: 2025-04-25 15:00:34.711737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d988d3a3121'
down_revision: Union[str, None] = '625160481821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Boolean(), nullable=False),
    sa.Column('bank_card', sa.Boolean(), nullable=False),
    sa.Column('account_number', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_methods')
    # ### end Alembic commands ###
