"""удалил ненужные таблицы,а также добавлю новую

Revision ID: 2e1daa876ad1
Revises: f69874358568
Create Date: 2025-04-23 14:25:44.590046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1daa876ad1'
down_revision: Union[str, None] = 'f69874358568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates_office_cashless_premium')
    op.drop_table('exchange_rates_office_cashless')
    op.drop_table('exchange_rates_internet_bank')
    op.drop_table('exchange_rates_office_cash')
    op.drop_table('exchange_rates_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates_cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('buy', sa.FLOAT(), nullable=False),
    sa.Column('sell', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates_office_cash',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('buy', sa.FLOAT(), nullable=False),
    sa.Column('sell', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates_internet_bank',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('buy', sa.FLOAT(), nullable=False),
    sa.Column('sell', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates_office_cashless',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('buy', sa.FLOAT(), nullable=False),
    sa.Column('sell', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates_office_cashless_premium',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('buy', sa.FLOAT(), nullable=False),
    sa.Column('sell', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
