"""удалил ненужные таблицы,а также добавлю новую

Revision ID: 33613fd35d83
Revises: e1cb68c91aaf
Create Date: 2025-04-23 13:11:59.900146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33613fd35d83'
down_revision: Union[str, None] = 'e1cb68c91aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
