"""создаю таблицу со связью один ко многим

Revision ID: 3a616dbc3a9a
Revises: a89bb187b4f6
Create Date: 2025-04-26 14:08:05.775480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a616dbc3a9a'
down_revision: Union[str, None] = 'a89bb187b4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('picture', sa.LargeBinary(), server_default=sa.text("(X'')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_country'), 'countries', ['country'], unique=True)
    op.create_table('exchange_methods_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('sell', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_methods_all_category'), 'exchange_methods_all', ['category'], unique=False)
    op.create_index(op.f('ix_exchange_methods_all_currency'), 'exchange_methods_all', ['currency'], unique=False)
    op.create_index('ix_exchange_rates_currency_category', 'exchange_methods_all', ['currency', 'category'], unique=False)
    op.create_table('servis_fitbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('question', backend.models.support_models.JSONText(), server_default='[]', nullable=True),
    sa.Column('answer', backend.models.support_models.JSONText(), server_default='[]', nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servis_fitbacks_category'), 'servis_fitbacks', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servis_fitbacks_category'), table_name='servis_fitbacks')
    op.drop_table('servis_fitbacks')
    op.drop_index('ix_exchange_rates_currency_category', table_name='exchange_methods_all')
    op.drop_index(op.f('ix_exchange_methods_all_currency'), table_name='exchange_methods_all')
    op.drop_index(op.f('ix_exchange_methods_all_category'), table_name='exchange_methods_all')
    op.drop_table('exchange_methods_all')
    op.drop_index(op.f('ix_countries_country'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
