"""дополнил таблицу с fitback

Revision ID: 59bb240d6ae4
Revises: 9320db5e3c0a
Create Date: 2025-04-22 21:10:41.487003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bb240d6ae4'
down_revision: Union[str, None] = '9320db5e3c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servis_fitbacks', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servis_fitbacks', 'message')
    # ### end Alembic commands ###
