"""начал делать банковские таблицы

Revision ID: 625160481821
Revises: 2e1daa876ad1
Create Date: 2025-04-25 14:46:47.826287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625160481821'
down_revision: Union[str, None] = '2e1daa876ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_banks_bank'), 'banks', ['bank'], unique=True)
    op.create_table('countries_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_bank_country'), 'countries_bank', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_bank_country'), table_name='countries_bank')
    op.drop_table('countries_bank')
    op.drop_index(op.f('ix_banks_bank'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
