"""добавил столбец

Revision ID: 74d5acc62547
Revises: 3ebb462738fb
Create Date: 2025-04-26 18:24:55.289987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d5acc62547'
down_revision: Union[str, None] = '3ebb462738fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_sistem', sa.Column('limit_min', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_sistem', 'limit_min')
    # ### end Alembic commands ###
