"""удалил таблицу

Revision ID: 88f6f6644c1e
Revises: f626330f29b1
Create Date: 2025-04-26 18:05:01.685294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f6f6644c1e'
down_revision: Union[str, None] = 'f626330f29b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_sistem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('commision', sa.Float(), nullable=False),
    sa.Column('limit_max', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bs_bank_country_method_curr', 'bank_sistem', ['bank', 'country', 'method', 'currency'], unique=False)
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_banks_name'), 'banks', ['name'], unique=True)
    op.create_table('countries_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_bank_country'), 'countries_bank', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_bank_country'), table_name='countries_bank')
    op.drop_table('countries_bank')
    op.drop_index(op.f('ix_banks_name'), table_name='banks')
    op.drop_table('banks')
    op.drop_index('ix_bs_bank_country_method_curr', table_name='bank_sistem')
    op.drop_table('bank_sistem')
    # ### end Alembic commands ###
