"""Изменил свойства таблицы - servis_fitbacks

Revision ID: 8bd24440e415
Revises: abc36d540e9a
Create Date: 2025-04-19 22:03:08.967971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.models.models import JSONText


# revision identifiers, used by Alembic.
revision: str = '8bd24440e415'
down_revision: Union[str, None] = 'abc36d540e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servis_fitbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('question', JSONText(), server_default='[]', nullable=False),
    sa.Column('answer', JSONText(), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servis_fitbacks_category'), 'servis_fitbacks', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servis_fitbacks_category'), table_name='servis_fitbacks')
    op.drop_table('servis_fitbacks')
    # ### end Alembic commands ###
