"""Изменил свойства таблицы - servis_fitbacks

Revision ID: 9320db5e3c0a
Revises: 8bd24440e415
Create Date: 2025-04-19 22:34:19.426061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9320db5e3c0a'
down_revision: Union[str, None] = '8bd24440e415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servis_fitbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('question', app.models.models.JSONText(), server_default='[]', nullable=True),
    sa.Column('answer', app.models.models.JSONText(), server_default='[]', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servis_fitbacks_category'), 'servis_fitbacks', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servis_fitbacks_category'), table_name='servis_fitbacks')
    op.drop_table('servis_fitbacks')
    # ### end Alembic commands ###
