"""удалил все таблиц

Revision ID: a89bb187b4f6
Revises: f3cb2d18da39
Create Date: 2025-04-25 22:45:18.665671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89bb187b4f6'
down_revision: Union[str, None] = 'f3cb2d18da39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_banks_bank'), 'banks', ['bank'], unique=True)
    op.create_table('countries_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_bank_country'), 'countries_bank', ['country'], unique=False)
    op.create_table('transfer_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Boolean(), nullable=False),
    sa.Column('bank_card', sa.Boolean(), nullable=False),
    sa.Column('account_number', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('methods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['methods_id'], ['transfer_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_table('transfer_methods')
    op.drop_index(op.f('ix_countries_bank_country'), table_name='countries_bank')
    op.drop_table('countries_bank')
    op.drop_index(op.f('ix_banks_bank'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
