"""Initial migration

Revision ID: c9c70cb0a340
Revises: ba8ebd48d93d
Create Date: 2025-04-16 16:53:20.169860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c70cb0a340'
down_revision: Union[str, None] = 'ba8ebd48d93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('picture', sa.LargeBinary(), server_default=sa.text("(X'')"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'picture')
    # ### end Alembic commands ###
