"""cоздал таблицу с servis_fitbacks 

Revision ID: d29116e17ede
Revises: 22ae72215c8b
Create Date: 2025-04-19 21:50:33.150334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29116e17ede'
down_revision: Union[str, None] = '22ae72215c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servis_fitbacks', 'question',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('servis_fitbacks', 'answer',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servis_fitbacks', 'answer',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('servis_fitbacks', 'question',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
