"""удалил ненужные таблицы,а также добавлю новую

Revision ID: e1cb68c91aaf
Revises: 3568a6be68ec
Create Date: 2025-04-23 12:04:31.172515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cb68c91aaf'
down_revision: Union[str, None] = '3568a6be68ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('internet_bank', sa.Float(), nullable=False),
    sa.Column('office_cash', sa.Float(), nullable=False),
    sa.Column('office_cashless', sa.Float(), nullable=False),
    sa.Column('office_cashless_premium', sa.Float(), nullable=False),
    sa.Column('cards', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_all_cards'), 'exchange_rates_all', ['cards'], unique=True)
    op.create_index(op.f('ix_exchange_rates_all_currency'), 'exchange_rates_all', ['currency'], unique=True)
    op.create_index(op.f('ix_exchange_rates_all_office_cash'), 'exchange_rates_all', ['office_cash'], unique=True)
    op.create_index(op.f('ix_exchange_rates_all_office_cashless'), 'exchange_rates_all', ['office_cashless'], unique=True)
    op.create_index(op.f('ix_exchange_rates_all_office_cashless_premium'), 'exchange_rates_all', ['office_cashless_premium'], unique=True)
    op.drop_table('exchange_rates_mobile_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates_mobile_app',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('buy', sa.FLOAT(), nullable=False),
    sa.Column('sell', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_exchange_rates_all_office_cashless_premium'), table_name='exchange_rates_all')
    op.drop_index(op.f('ix_exchange_rates_all_office_cashless'), table_name='exchange_rates_all')
    op.drop_index(op.f('ix_exchange_rates_all_office_cash'), table_name='exchange_rates_all')
    op.drop_index(op.f('ix_exchange_rates_all_currency'), table_name='exchange_rates_all')
    op.drop_index(op.f('ix_exchange_rates_all_cards'), table_name='exchange_rates_all')
    op.drop_table('exchange_rates_all')
    # ### end Alembic commands ###
