"""удалил ненужные таблицы,а также добавлю новую

Revision ID: e919b66dfe6a
Revises: 33613fd35d83
Create Date: 2025-04-23 13:36:16.875493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e919b66dfe6a'
down_revision: Union[str, None] = '33613fd35d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_methods_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('sell', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_methods_all_category'), 'exchange_methods_all', ['category'], unique=False)
    op.create_index(op.f('ix_exchange_methods_all_currency'), 'exchange_methods_all', ['currency'], unique=False)
    op.create_index('ix_exchange_rates_currency_category', 'exchange_methods_all', ['currency', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exchange_rates_currency_category', table_name='exchange_methods_all')
    op.drop_index(op.f('ix_exchange_methods_all_currency'), table_name='exchange_methods_all')
    op.drop_index(op.f('ix_exchange_methods_all_category'), table_name='exchange_methods_all')
    op.drop_table('exchange_methods_all')
    # ### end Alembic commands ###
