"""Initial migration

Revision ID: ebd5f1b3915a
Revises: c9c70cb0a340
Create Date: 2025-04-16 17:17:32.884712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd5f1b3915a'
down_revision: Union[str, None] = 'c9c70cb0a340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'picture',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("(X'')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'picture',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=False,
               existing_server_default=sa.text("(X'')"))
    # ### end Alembic commands ###
