"""начал делать банковские таблицы

Revision ID: f3cb2d18da39
Revises: 2d988d3a3121
Create Date: 2025-04-25 15:06:49.264783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cb2d18da39'
down_revision: Union[str, None] = '2d988d3a3121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('methods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['methods_id'], ['transfer_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
