"""удалил ненужные таблицы,а также добавлю новую

Revision ID: f69874358568
Revises: e919b66dfe6a
Create Date: 2025-04-23 13:44:35.441712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69874358568'
down_revision: Union[str, None] = 'e919b66dfe6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_methods_all', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_methods_all', 'quantity')
    # ### end Alembic commands ###
