"""описание ваших новых изменений

Revision ID: f6e36504a568
Revises: 6be457385f05
Create Date: 2025-04-19 20:34:37.153058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e36504a568'
down_revision: Union[str, None] = '6be457385f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servis_fitbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer'),
    sa.UniqueConstraint('question')
    )
    op.create_index(op.f('ix_servis_fitbacks_category'), 'servis_fitbacks', ['category'], unique=True)
    op.drop_table('fitbacks_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitbacks_chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_servis_fitbacks_category'), table_name='servis_fitbacks')
    op.drop_table('servis_fitbacks')
    # ### end Alembic commands ###
